### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by lvshaoli** [gaojinhsu/VideoFullScreenDemo#1]
"github.com/gaojinhsu/SharkVision_MediaServer/log" 这个库是您写的吗，如果是麻烦给一下，找不到库跑不起来

**Comment by gaojinhsu** [comment]
> "github.com/gaojinhsu/SharkVision_MediaServer/log" 这个库是您写的吗，如果是麻烦给一下，找不到库跑不起来

已经发了份最新的代码给你们的负责人了。
